baseurl = "https://tokio.rs"
title = "Tokio"
languageCode = "en-us"
canonifyURLs = "true"
googleAnalytics = "UA-90234741-1"

[params]
futuresDocsURL = "https://docs.rs/futures/0.1/futures"
coreDocsURL = "https://docs.rs/tokio-core/0.1/tokio_core"
protoDocsURL = "https://tokio-rs.github.io/tokio-proto/tokio_proto"
serviceDocsURL = "https://tokio-rs.github.io/tokio-service/tokio_service"
